Freeze and unfreeze account requests is added to accounts
unit-finance/unit-node-sdk pull request #112
Opened 2022-02-07 18:12 UTC by Bluedot-Dev

Freeze and unfreeze account request are added to account.ts. FreezeAccount type is also added to types. Please review my code!

Thanks

2022-02-08 16:31 UTC, axshani requested changes
thanks for this pr, I left you few comments

2022-02-08 16:31 UTC, axshani commented on resources/account.ts
> +    public async unFreezeAccount(accountId: string): Promise<UnitResponse<Account>> {
please rename the function to unfreezeAccount

2022-02-08 16:31 UTC, axshani commented on types/account.ts
> +            reasonText: string
the type of reason is 'Fraud' or 'Other' and reasonText should be optional

2022-02-13 09:41 UTC, ilyamerman approved these changes

2022-02-13 09:42 UTC, merged