Webhooks
unit-finance/unit-node-sdk pull request #15
Opened 2021-06-26 10:11 UTC by axshani

Unit uses webhooks to notify your application when an event occurs.
The content type is JsonAPI

2021-06-28 16:06 UTC, Elroie requested changes

2021-07-05 17:37 UTC, axshani commented on resources/webhooks.ts
> +    public async list(params?: WebhookListParams): Promise<UnitResponse<Webhook[]> | UnitError> {
it's already located at resources/webhooks

2021-07-06 15:18 UTC, ilyamerman approved these changes

2021-07-06 15:47 UTC, Elroie commented on package.json
> +  "version": "0.3.0",
remove?

2021-07-07 06:37 UTC, axshani commented on package.json
> +  "version": "0.3.0",
done

2021-07-07 08:27 UTC, merged