Payments
unit-finance/unit-node-sdk pull request #16
Opened 2021-07-01 21:25 UTC by axshani

Implemented Payments resource

2021-07-04 16:09 UTC, Elroie requested changes

2021-07-04 16:09 UTC, Elroie commented on package.json
> +  "version": "0.4.0",
```suggestion
  "version": "0.2.16",
```

2021-07-06 15:44 UTC, ilyamerman approved these changes

2021-07-06 15:46 UTC, Elroie approved these changes

2021-07-06 15:48 UTC, ilyamerman requested changes
Everything is well, just "ACH" => "Ach" :)

2021-07-06 15:48 UTC, ilyamerman commented on types/payments.ts
> +export type Payment = ACHPayment | BookPayment
```suggestion
export type Payment = AchPayment | BookPayment
```

2021-07-06 15:48 UTC, ilyamerman commented on types/payments.ts
> +export interface ACHPayment {
```suggestion
export interface AchPayment {
```

2021-07-07 08:36 UTC, merged