Make setting User-Agent optional
unit-finance/unit-node-sdk pull request #188
Opened 2022-06-08 02:56 UTC by luoyang9

Allow the setting of the User-Agent header to be configurable. This allows us to use this SDK on the browser without having User-Agent errors pop up in console.

2022-06-09 13:14 UTC, axshani commented
Hey! thanks for the PR, I left some comments :)

2022-06-10 03:07 UTC, luoyang9 commented
Hi @axshani! I can't seem to find the comments that you left, could you repost them?

2022-06-12 05:46 UTC, axshani requested changes

2022-06-12 05:46 UTC, axshani commented on resources/baseResource.ts
> +            ...(config?.shouldSkipUserAgent ? {} : { "User-Agent": "unit-node-sdk" }),
please change to:
...(config?.sdkUserAgent && { "User-Agent": "unit-node-sdk" })

2022-06-12 05:46 UTC, axshani commented on types/common.ts
> +    shouldSkipUserAgent?: boolean
sdkUserAgent

2022-06-12 05:47 UTC, axshani commented
> Hi @axshani! I can't seem to find the comments that you left, could you repost them?

Hope you can see them now

2022-06-17 05:28 UTC, luoyang9 commented
@axshani updated!

2022-06-19 11:27 UTC, ilyamerman approved these changes

2022-06-19 11:27 UTC, merged