Add bulk payment create method on Payments resource
unit-finance/unit-node-sdk pull request #284
Opened 2022-11-29 05:38 UTC by evang859

Unit docs: https://docs.unit.co/payments#bulk-payments

Related Issue: https://github.com/unit-finance/unit-node-sdk/issues/277

2022-11-29 08:42 UTC, axshani requested changes

2022-11-29 08:42 UTC, axshani commented on types/payments.ts
> +export interface CreateBulkPaymentResponse {
let's call it 
BulkPayments

2022-11-29 12:05 UTC, evang859 commented on types/payments.ts
> +export interface CreateBulkPaymentResponse {
sounds good - done

2022-11-30 11:19 UTC, axshani approved these changes
Great! Thanks again

2022-12-01 08:47 UTC, merged