make CardLevelLimits properties optional
unit-finance/unit-node-sdk pull request #422
Opened 2023-12-20 20:40 UTC by randallmlough

Update the CardLevelLimits interface to have optional properties

2023-12-21 14:08 UTC, axshani commented
Thanks for the PR! I ran the CI and npm-lint is failing
```
Error:   1:83  error  Strings must use doublequote  @typescript-eslint/quotes
Error:   1:93  error  Extra semicolon               @typescript-eslint/semi
```
can you please fix this? :)

2023-12-21 14:09 UTC, axshani requested changes
Thanks for the PR! I ran the CI and npm-lint is failing

can you please fix this? :)

2023-12-22 17:40 UTC, randallmlough commented
> Thanks for the PR! I ran the CI and npm-lint is failing
> 
> can you please fix this? :)

Fixed. Let me know if theres anything more I need to do.

2023-12-28 11:59 UTC, ilyamerman approved these changes

2023-12-28 11:59 UTC, merged