add ApplicationForm type + get method
unit-finance/unit-node-sdk pull request #45
Opened 2021-08-02 14:00 UTC by jerrywang-hiatus

Adding missing get method for applicationForms. 

I'm not quite sure of the interface for ApplicationForm as it's not documented. I just went by the response from the API so there are a few `TODO` in the interface to fill in.

2021-08-15 08:12 UTC, ilyamerman requested changes

2021-08-15 08:12 UTC, ilyamerman commented on types/applicationForm.ts
> +}
Hey @jerrywang-hiatus :)

Sorry for the long delay,
We are in the process of updating the docs regarding the application form, some of the properties that were previously returned have been omitted from the API call (they were more relevant to the actual UI).
The only properties that will be returned in the `create` and `get` endpoints will be: `tags, url, stage, applicantDetails` (You can see https://docs.unit.co/#create-application-form response section for more details).

Other than that everything looks great, and ApplicationForm as a resource will soon be updated in the docs (including relationship information)

Will tell you once it's live!

Thanks :)

2021-08-16 11:04 UTC, ilyamerman commented on types/applicationForm.ts
> +}
Hi again, here's the relevant new docs section about the ApplicationForm resource: https://docs.unit.co/#applicationform

2021-09-03 15:44 UTC, jerrywang-hiatus commented
Had some time to get back on this. Updated the interface with what's documented.

2021-09-14 06:48 UTC, ilyamerman approved these changes

2021-09-14 08:29 UTC, merged